
# Default plot settings
plot:
  color: blue
  title: SpaceX Data Analysis
  x_axis_title: X-axis
  y_axis_title: Y-axis
  font_size: 24
  font_name: Comic Sans
  figure_size:
    width: 10
    height: 6
  default_save_path: /path/to/save/plots/